# Generated by Django 4.2.1 on 2023-06-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgre_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='john', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='doe', max_length=255),
        ),
    ]
