# Generated by Django 4.2.1 on 2023-06-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgre_api', '0002_user_name_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(default='female', max_length=20),
        ),
    ]
